### PR TITLE
Update Makefile to work with variant lua versions. Update README

### PR DESCRIPTION
**Pull request by berwynhoyt**
- Pick include path default to match user's default lua, and make it easier to override.
- Update README to match

### CODE REVIEW

**Comment by orbitalquark** [comment]
How about just defaulting to `/usr/include/lua5.4` instead of invoking the interpreter, which introduces another dependency? (By the way, try using `lua --version` instead of your method.)

In an ideal world we would be using `pkg-config`, but for user installs, this often does not exist.

**Comment by berwynhoyt** [comment]
Yes, I considered defaulting to Lua 5.4, and I'm not opposed. However, for your consideration, these were the reasons I did not:

1. We already have a dependency on Lua when running tests in the last line of the Makefile. Since our tests need to run in a particular version of Lua, I thought it made sense to build it with that version, too.
2. I considered using 'lua -v' (there is no --version), but extracting the version number would still require an additional dependency on, say, grep (grep -oE "[0-9]+\.[0-9]+"). The grep version looks simpler but is riskier if the 'lua -v' output format ever changes, and it adds a dependency. Or we could use lua which we already depend on.
3. I was afraid of annoying you or anyone who is not using lua 5.4. However, my addition of a lua_version make variable does make it easier to override that.
4. I agree with you on avoiding pkg-config, and for the same reason.

Cheers.

**Comment by ksbhaskar** [comment]
Since YottaDB would already be installed on the system, you can use it, e.g.,

```
$ yottadb -run %XCMD 'write $zparse("/usr/lib/liblua.so",,,,"symlink"),!'
/usr/lib/liblua.so.5.4.4
$ yottadb -run %XCMD 'write $zpiece($zparse("/usr/lib/liblua.so",,,,"symlink"),"liblua.so.",2),!'
5.4.4
$ 
```

**Comment by orbitalquark** [comment]
Let's build using Lua 5.4 by default then. Thanks.

**Comment by berwynhoyt** [comment]
Mitchell, just changing all the 5.3 figures to 5.4 in the Makefile like you have done, doesn't really do the job as I have to build and test this against several different lua versions on the same system. Even if you don't want to auto-detect language, can you at the very least implement the $lua_version variable that I suggested, as this lets the make user override the lua version. Thanks.

**Comment by orbitalquark** [comment]
You are correct. I went ahead and applied your suggested patch. Sorry about that. Thanks for your patience.

**Comment by berwynhoyt** [comment]
Thank you. :-)

**Pull request closed without merging**
