### PR TITLE
Update to build and test against the latest version of ydb (1.34)

### PR DESCRIPTION
**Pull request by berwynhoyt**

### CODE REVIEW

**Comment by berwynhoyt** [comment]
Mitchell, I'm working in conjunction with the Anet Library. I would like to get in touch. I'd also want to chat about the zwrite change. Can you make contact? My email is firstname.lastname@gmail.com

**Comment by orbitalquark** [comment]
Thanks for your contribution :) I have committed the following:

https://github.com/orbitalquark/lua-yottadb/commit/5f1607f65f5c72c7d294b95f1194c0f6176e9f6e: Added .gitignore
https://github.com/orbitalquark/lua-yottadb/commit/31bb4a078b3e35f5deb71831bc601febb9063f70: Added 'make clean' rule
https://github.com/orbitalquark/lua-yottadb/commit/21ce43620bf7ff66ff086147be350057c9acc01d: Allow passing 'TESTS' to 'make test'
https://github.com/orbitalquark/lua-yottadb/commit/0d776aacdfccd7d0fb73bb4d9953d113bc011675: Require YottaDB 1.34 by updating calling interface

Since there is a security concern in external interfaces prior to 1.34, I don't think it's worth supporting those prior versions.

**Comment by orbitalquark** [comment]
By the way, I did not commit the proposed zwrite change because `{...}` works for me as well as `(...)`. I'd like to better understand why that change should be made. The test code is based on the Python wrapper and could be an additional test in itself that `{...}` and `(...)` are interchangeable.

**Comment by orbitalquark** [comment]
Never mind, I was wrong about the Python wrapper using those strings. I have committed https://github.com/orbitalquark/lua-yottadb/commit/ba0c7ee0b7b7369d66833c58e0210cfe205823b8 to use `(...)` as you suggested. Sorry about that.

**Pull request closed without merging**
